[package]
name = "cxxbridge_cmd"
version = "1.0.94"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
clap = { version = "4.2.1", dependencies = ["clap_builder"] }
clap_builder = { version = "4.2.1", dependencies = ["bitflags", "clap_lex", "strsim"] }
clap_lex = "0.4.1"
codespan-reporting = { version = "0.11.1", dependencies = ["termcolor", "unicode-width"] }
proc-macro2 = { version = "1.0.56", dependencies = ["unicode-ident"] }
quote = { version = "1.0.26", dependencies = ["proc-macro2"] }
strsim = "0.10.0"
syn = { version = "2.0.13", dependencies = ["proc-macro2", "quote", "unicode-ident"] }
termcolor = { version = "1.2.0", dependencies = ["winapi-util"] }
unicode-ident = "1.0.8"
unicode-width = "0.1.10"
winapi = { version = "0.3.9", dependencies = ["winapi-i686-pc-windows-gnu", "winapi-x86_64-pc-windows-gnu"] }
winapi-i686-pc-windows-gnu = "0.4.0"
winapi-util = { version = "0.1.5", dependencies = ["winapi"] }
winapi-x86_64-pc-windows-gnu = "0.4.0"
