[package]
name = "cxxbridge_cmd"
version = "1.0.94"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
clap = "4.2.1"
clap_builder = "4.2.1"
clap_lex = "0.4.1"
codespan-reporting = "0.11.1"
proc-macro2 = "1.0.56"
quote = "1.0.26"
strsim = "0.10.0"
syn = "2.0.13"
termcolor = "1.2.0"
unicode-ident = "1.0.8"
unicode-width = "0.1.10"
winapi = "0.3.9"
winapi-i686-pc-windows-gnu = "0.4.0"
winapi-util = "0.1.5"
winapi-x86_64-pc-windows-gnu = "0.4.0"
