# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gem/calculators/plugin/qdrant/optionspb/qdrant_search_calculator_options.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nRsrc/gem/calculators/plugin/qdrant/optionspb/qdrant_search_calculator_options.proto\x12$gml.gem.calculators.qdrant.optionspb\"\x90\x01\n\x1dQdrantSearchCalculatorOptions\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\x12\x1e\n\ncollection\x18\x02 \x01(\tR\ncollection\x12\x14\n\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x1f\n\x0bpayload_key\x18\x04 \x01(\tR\npayloadKeyBLZJgimletlabs.ai/gimlet/src/gem/calculators/plugin/qdrant/optionspb;optionspbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.gem.calculators.plugin.qdrant.optionspb.qdrant_search_calculator_options_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZJgimletlabs.ai/gimlet/src/gem/calculators/plugin/qdrant/optionspb;optionspb'
  _QDRANTSEARCHCALCULATOROPTIONS._serialized_start=125
  _QDRANTSEARCHCALCULATOROPTIONS._serialized_end=269
# @@protoc_insertion_point(module_scope)
