---
run:
  timeout: 5m
output:
  sort-results: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
  - asciicheck
  - errcheck
  - gci
  - godot
  - gofumpt
  - gosimple
  - govet
  - importas
  - ineffassign
  - loggercheck
  - makezero
  - misspell
  - nakedret
  - nolintlint
  - nonamedreturns
  - predeclared
  - revive
  - staticcheck
  - testifylint
  - testpackage
  - typecheck
  - unused
  - wastedassign
  - whitespace
linters-settings:
  errcheck:
    exclude-functions:
    - (*database/sql.Tx).Rollback
    - (*nhooyr.io/websocket.Conn).CloseNow
    - (github.com/nats-io/nats.go/jetstream.Msg).Ack
    - (github.com/nats-io/nats.go/jetstream.Msg).Nak
  gci:
    sections:
    - standard
    - default
    - prefix(gimletlabs.ai/gimlet)
    custom-order: true
  importas:
    no-unaliased: true
    alias:
    - pkg: github.com/sirupsen/logrus
      alias: log
  nakedret:
    max-func-lines: 0
  revive:
    confidence: 0.1
    ignore-generated-header: true
    enable-all-rules: true
    severity: error
    rules:
    - name: add-constant
      disabled: true
    - name: argument-limit
      disabled: true
    - name: banned-characters
      disabled: true
    - name: cognitive-complexity
      disabled: true
    - name: comment-spacings
      arguments:
      - exhaustive
    - name: confusing-naming
      disabled: true
    - name: confusing-results
      disabled: true
    - name: cyclomatic
      disabled: true
    - name: deep-exit
      disabled: true
    - name: defer
      disabled: true
    - name: file-header
      disabled: true
    - name: flag-parameter
      disabled: true
    - name: function-length
      disabled: true
    - name: function-result-limit
      disabled: true
    - name: line-length-limit
      disabled: true
    - name: max-public-structs
      disabled: true
    - name: nested-structs
      disabled: true
    - name: optimize-operands-order
      disabled: true
    - name: unchecked-type-assertion
      arguments:
      - acceptIgnoredAssertionResult: true
    - name: unhandled-error
      disabled: true
