---
APPLY_FIXES: all
ENABLE_LINTERS:
- ACTION_ACTIONLINT
- BUILDIFIER
- BASH_SHELLCHECK
- BASH_SHFMT
- CSS_STYLELINT
- EDITORCONFIG_EDITORCONFIG_CHECKER
- LICENSE_CHECKER
- TERRAFORM_TFLINT
# TODO(michelle/zasgar): Consider enabling after auditing the rules and current set of lint issues.
# - TERRAFORM_TERRASCAN
# TODO(vihang): Enable this after rubucop is faster.
# - RUBY_RUBOCOP
- TERRAFORM_TERRAFORM_FMT
- YAML_V8R
- YAML_YAMLLINT
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FILEIO_REPORTER: false
REPORT_OUTPUT_FOLDER: none
SHOW_ELAPSED_TIME: true
PLUGINS:
- file://tools/linters/mega-linter-plugin-licenses/licenses.megalinter-descriptor.yml
- file://tools/linters/mega-linter-plugin-bazel/bazel.megalinter-descriptor.yml
FILTER_REGEX_EXCLUDE: (pnpm-lock.yaml|go_deps.bzl)

# Linter specific configs
CSS_STYLELINT_CONFIG_FILE: LINTER_DEFAULT
# The mega-linter json schema is broken with plugins, so don't check the schema.
YAML_V8R_FILTER_REGEX_EXCLUDE: (.mega-linter.yml)
YAML_YAMLLINT_ARGUMENTS: '--strict'
