---
APPLY_FIXES: all
ENABLE_LINTERS:
- ACTION_ACTIONLINT
- BUILDIFIER
- BASH_SHELLCHECK
- BASH_SHFMT
- BUF_BREAKCHECK
- BUF_LINT
- CSS_STYLELINT
- CLANG_FORMAT
- EDITORCONFIG_EDITORCONFIG_CHECKER
- LICENSE_CHECKER
- PYTHON_BLACK
- PYTHON_ISORT
# TODO(vihang): Enable this after rubucop is faster.
# - RUBY_RUBOCOP
- TERRAFORM_TERRAFORM_FMT
# TODO(michelle/zasgar): Consider enabling after auditing the rules and current set of lint issues.
# - TERRAFORM_TERRASCAN
- TERRAFORM_TFLINT
- TSX_ESLINT
- TYPESCRIPT_ES
- TYPESCRIPT_PRETTIER
- YAML_V8R
- YAML_YAMLLINT
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FILEIO_REPORTER: false
FORMATTERS_DISABLE_ERRORS: false
SHOW_ELAPSED_TIME: true
PLUGINS:
- file://tools/linters/mega-linter-plugin-bazel/bazel.megalinter-descriptor.yml
- file://tools/linters/mega-linter-plugin-buf/buf.megalinter-descriptor.yml
- file://tools/linters/mega-linter-plugin-cpp/cpp.megalinter-descriptor.yml
- file://tools/linters/mega-linter-plugin-licenses/licenses.megalinter-descriptor.yml
FILTER_REGEX_EXCLUDE: (app\/graphql-schema.ts|pnpm-lock.yaml|infra\/credentials/*|gazelle_python.yaml)

# Linter specific configs
CSS_STYLELINT_CONFIG_FILE: LINTER_DEFAULT
# See https://github.com/oxsecurity/megalinter/issues/2699
TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES: GITHUB_TOKEN
TSX_ESLINT_CONFIG_FILE: src/ui/.eslintrc.js
TSX_ESLINT_FILE_EXTENSIONS: [".jsx", ".tsx"]
TSX_ESLINT_RULES_PATH: src/ui
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_ES_CONFIG_FILE: src/ui/.eslintrc.js
TYPESCRIPT_ES_RULES_PATH: src/ui
TYPESCRIPT_FILE_EXTENSIONS: [".js", ".ts"]
TYPESCRIPT_PRETTIER_CONFIG_FILE: src/ui/.prettierrc.json
TYPESCRIPT_PRETTIER_FILE_EXTENSIONS: [".js", ".jsx", ".ts", ".tsx"]
TYPESCRIPT_PRETTIER_RULES_PATH: src/ui
# The mega-linter json schema is broken with plugins, so don't check the schema.
YAML_V8R_FILTER_REGEX_EXCLUDE: (.mega-linter.yml)
YAML_YAMLLINT_ARGUMENTS: '--strict'
