---
extends:
- stylelint-config-standard
rules:
  at-rule-no-unknown:
  - true
  - ignoreAtRules:
    - tailwind
    - apply
    - variants
    - responsive
    - screen
  custom-property-empty-line-before: null
  no-descending-specificity: null
