---
extends: default

rules:
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: false
    check-multi-line-strings: true
  line-length:
    max: 120
  truthy:
    check-keys: false
