[toolchain]
channel = "1.80.0"
components = [
  "cargo",
  "clippy",
  "llvm-tools",
  "rust-std",
  "rustc",
]
targets = [
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-gnu",
]
profile = "minimal"
