# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gem/calculators/plugin/cpu_tensor/optionspb/bounding_box_tensors_to_detections_options.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n`src/gem/calculators/plugin/cpu_tensor/optionspb/bounding_box_tensors_to_detections_options.proto\x12(gml.gem.calculators.cpu_tensor.optionspb\"F\n\x1e\x42oundingBoxToDetectionsOptions\x12$\n\x0eindex_to_label\x18\x01 \x03(\tR\x0cindexToLabelBPZNgimletlabs.ai/gimlet/src/gem/calculators/plugin/cpu_tensor/optionspb;optionspbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.gem.calculators.plugin.cpu_tensor.optionspb.bounding_box_tensors_to_detections_options_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZNgimletlabs.ai/gimlet/src/gem/calculators/plugin/cpu_tensor/optionspb;optionspb'
  _BOUNDINGBOXTODETECTIONSOPTIONS._serialized_start=142
  _BOUNDINGBOXTODETECTIONSOPTIONS._serialized_end=212
# @@protoc_insertion_point(module_scope)
