# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gem/calculators/plugin/cpu_tensor/optionspb/bounding_box_tensors_to_detections_options.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n`src/gem/calculators/plugin/cpu_tensor/optionspb/bounding_box_tensors_to_detections_options.proto\x12(gml.gem.calculators.cpu_tensor.optionspb\"\x83\x03\n\x1e\x42oundingBoxToDetectionsOptions\x12$\n\x0eindex_to_label\x18\x01 \x03(\tR\x0cindexToLabel\x12\x86\x01\n\x11\x63oordinate_format\x18\x02 \x01(\x0e\x32Y.gml.gem.calculators.cpu_tensor.optionspb.BoundingBoxToDetectionsOptions.CoordinateFormatR\x10\x63oordinateFormat\"\xb1\x01\n\x10\x43oordinateFormat\x12\x1d\n\x19\x43OORDINATE_FORMAT_UNKNOWN\x10\x00\x12%\n!COORDINATE_FORMAT_DIAG_CORNERS_YX\x10\x01\x12%\n!COORDINATE_FORMAT_CENTER_ANCHORED\x10\x02\x12\x30\n,COORDINATE_FORMAT_NORMALIZED_DIAG_CORNERS_XY\x10\x03\x42PZNgimletlabs.ai/gimlet/src/gem/calculators/plugin/cpu_tensor/optionspb;optionspbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.gem.calculators.plugin.cpu_tensor.optionspb.bounding_box_tensors_to_detections_options_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZNgimletlabs.ai/gimlet/src/gem/calculators/plugin/cpu_tensor/optionspb;optionspb'
  _BOUNDINGBOXTODETECTIONSOPTIONS._serialized_start=143
  _BOUNDINGBOXTODETECTIONSOPTIONS._serialized_end=530
  _BOUNDINGBOXTODETECTIONSOPTIONS_COORDINATEFORMAT._serialized_start=353
  _BOUNDINGBOXTODETECTIONSOPTIONS_COORDINATEFORMAT._serialized_end=530
# @@protoc_insertion_point(module_scope)
