graph {
  input_side_packet: "tensorrt_exec_ctx"
  input_side_packet: "cpu_exec_ctx"
  input_side_packet: "ctrl_exec_ctx"
  input_side_packet: "frame_rate"

  node {
    calculator: "ArgusCamSourceSubgraph"
    output_stream: "frames"
    input_stream: "FINISHED:detections"
    output_stream: "ALLOW:frame_allowed"
  }
  node {
    calculator: "VideoEncoderSubgraph"
    input_side_packet: "FRAME_RATE:frame_rate"
    input_stream: "frames"
    output_stream: "video"
  }
  node {
    calculator: "YoloModelTensorRTSubgraph"
    input_side_packet: "CPU_EXEC_CTX:cpu_exec_ctx"
    input_side_packet: "TENSORRT_EXEC_CTX:tensorrt_exec_ctx"
    input_stream: "frames"
    output_stream: "detections"
  }
  node {
    calculator: "ObjDetectionOverlayedVideoSinkSubgraph"
    input_side_packet: "EXEC_CTX:ctrl_exec_ctx"
    input_stream: "AV_PACKETS:video"
    input_stream: "DETECTIONS:detections"
  }
}
model_spec {
  onnx_blob_key: "yolov3.onnx"
  onnx_file {
    size_bytes: 0
    sha256_hash: ""
  }
  runtime: "TensorRT"
  tensorrt_spec {
    optimization_profile {
      tensor_shape_range {
        tensor_name: "input_1"
        dim: 1
        dim: 3
        dim: 416
        dim: 416
      }
      tensor_shape_range {
        tensor_name: "image_shape"
        dim: 1
        dim: 2
      }
    }
    engine_blob_key: "yolov3.engine"
  }
}
