// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: src/api/corepb/v1/controlplane.proto

package corepb

import (
	fmt "fmt"
	typespb "gimletlabs.ai/gimlet/src/common/typespb"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CPTopic int32

const (
	CP_TOPIC_UNKNOWN          CPTopic = 0
	CP_TOPIC_DEVICE_CONNECTED CPTopic = 1
)

var CPTopic_name = map[int32]string{
	0: "CP_TOPIC_UNKNOWN",
	1: "CP_TOPIC_DEVICE_CONNECTED",
}

var CPTopic_value = map[string]int32{
	"CP_TOPIC_UNKNOWN":          0,
	"CP_TOPIC_DEVICE_CONNECTED": 1,
}

func (CPTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7c2de589f3a2dd8, []int{0}
}

type DeviceConnected struct {
	DeviceID *typespb.UUID `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
}

func (m *DeviceConnected) Reset()      { *m = DeviceConnected{} }
func (*DeviceConnected) ProtoMessage() {}
func (*DeviceConnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c2de589f3a2dd8, []int{0}
}
func (m *DeviceConnected) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceConnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceConnected.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeviceConnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceConnected.Merge(m, src)
}
func (m *DeviceConnected) XXX_Size() int {
	return m.Size()
}
func (m *DeviceConnected) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceConnected.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceConnected proto.InternalMessageInfo

func (m *DeviceConnected) GetDeviceID() *typespb.UUID {
	if m != nil {
		return m.DeviceID
	}
	return nil
}

func init() {
	proto.RegisterEnum("gml.internal.api.core.v1.CPTopic", CPTopic_name, CPTopic_value)
	proto.RegisterType((*DeviceConnected)(nil), "gml.internal.api.core.v1.DeviceConnected")
}

func init() {
	proto.RegisterFile("src/api/corepb/v1/controlplane.proto", fileDescriptor_f7c2de589f3a2dd8)
}

var fileDescriptor_f7c2de589f3a2dd8 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xb3, 0x97, 0xff, 0xbf, 0x46, 0xa1, 0x25, 0xf4, 0x50, 0x0b, 0x1d, 0x45, 0x3c, 0x88,
	0xe0, 0x2e, 0xd5, 0x9b, 0x82, 0x87, 0x6e, 0x72, 0x08, 0x62, 0x5a, 0xa4, 0x55, 0xf0, 0x12, 0x92,
	0xcd, 0x12, 0x16, 0x92, 0xdd, 0x25, 0x4d, 0x0b, 0xde, 0x7c, 0x04, 0x1f, 0xc3, 0x47, 0xf1, 0xd8,
	0x63, 0x4f, 0x62, 0xb7, 0x17, 0x8f, 0x7d, 0x04, 0x49, 0x02, 0x5e, 0xbc, 0x7d, 0xf3, 0xcd, 0xef,
	0x9b, 0x61, 0xc6, 0x3e, 0x9d, 0x17, 0x8c, 0x44, 0x5a, 0x10, 0xa6, 0x0a, 0xae, 0x63, 0xb2, 0x1c,
	0x12, 0xa6, 0x64, 0x59, 0xa8, 0x4c, 0x67, 0x91, 0xe4, 0x58, 0x17, 0xaa, 0x54, 0x4e, 0x2f, 0xcd,
	0x33, 0x2c, 0x64, 0xc9, 0x0b, 0x19, 0x65, 0x38, 0xd2, 0x02, 0x57, 0x38, 0x5e, 0x0e, 0xfb, 0xdd,
	0x54, 0xa5, 0xaa, 0x86, 0x48, 0xa5, 0x1a, 0xbe, 0x3f, 0xa8, 0xa6, 0x32, 0x95, 0xe7, 0x4a, 0x92,
	0xf2, 0x45, 0xf3, 0xb9, 0x8e, 0xc9, 0x62, 0x21, 0x92, 0xa6, 0x7d, 0x72, 0x6f, 0xb7, 0x5d, 0xbe,
	0x14, 0x8c, 0x53, 0x25, 0x25, 0x67, 0x25, 0x4f, 0x9c, 0x6b, 0x7b, 0x2f, 0xa9, 0xad, 0x50, 0x24,
	0x3d, 0x74, 0x8c, 0xce, 0xf6, 0x2f, 0xdb, 0xb8, 0xda, 0x5a, 0xc7, 0xf1, 0x6c, 0xe6, 0xbb, 0xa3,
	0x03, 0xf3, 0x79, 0xd4, 0x6a, 0x82, 0xbe, 0xfb, 0xd0, 0x6a, 0x78, 0x3f, 0x39, 0xbf, 0xb5, 0xff,
	0xd3, 0xc9, 0x54, 0x69, 0xc1, 0x9c, 0xae, 0xdd, 0xa1, 0x93, 0x70, 0x3a, 0x9e, 0xf8, 0x34, 0x9c,
	0x05, 0x77, 0xc1, 0xf8, 0x29, 0xe8, 0x58, 0xce, 0xc0, 0x3e, 0xfc, 0x75, 0x5d, 0xef, 0xd1, 0xa7,
	0x5e, 0x48, 0xc7, 0x41, 0xe0, 0xd1, 0xa9, 0xe7, 0x76, 0xd0, 0x88, 0xad, 0x36, 0x60, 0xad, 0x37,
	0x60, 0xed, 0x36, 0x80, 0x5e, 0x0d, 0xa0, 0x77, 0x03, 0xe8, 0xc3, 0x00, 0x5a, 0x19, 0x40, 0x5f,
	0x06, 0xd0, 0xb7, 0x01, 0x6b, 0x67, 0x00, 0xbd, 0x6d, 0xc1, 0x5a, 0x6d, 0xc1, 0x5a, 0x6f, 0xc1,
	0x7a, 0xbe, 0x48, 0x45, 0x9e, 0xf1, 0x32, 0x8b, 0xe2, 0x39, 0x8e, 0x04, 0x69, 0x2a, 0xf2, 0xe7,
	0x9d, 0x37, 0x8d, 0x8a, 0xff, 0xd5, 0xa7, 0x5f, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x48, 0x75,
	0x4c, 0x59, 0x71, 0x01, 0x00, 0x00,
}

func (x CPTopic) String() string {
	s, ok := CPTopic_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *DeviceConnected) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DeviceConnected)
	if !ok {
		that2, ok := that.(DeviceConnected)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DeviceID.Equal(that1.DeviceID) {
		return false
	}
	return true
}
func (this *DeviceConnected) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&corepb.DeviceConnected{")
	if this.DeviceID != nil {
		s = append(s, "DeviceID: "+fmt.Sprintf("%#v", this.DeviceID)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringControlplane(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *DeviceConnected) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceConnected) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeviceConnected) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeviceID != nil {
		{
			size, err := m.DeviceID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintControlplane(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintControlplane(dAtA []byte, offset int, v uint64) int {
	offset -= sovControlplane(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DeviceConnected) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DeviceID != nil {
		l = m.DeviceID.Size()
		n += 1 + l + sovControlplane(uint64(l))
	}
	return n
}

func sovControlplane(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozControlplane(x uint64) (n int) {
	return sovControlplane(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *DeviceConnected) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeviceConnected{`,
		`DeviceID:` + strings.Replace(fmt.Sprintf("%v", this.DeviceID), "UUID", "typespb.UUID", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringControlplane(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *DeviceConnected) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowControlplane
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceConnected: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceConnected: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthControlplane
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthControlplane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeviceID == nil {
				m.DeviceID = &typespb.UUID{}
			}
			if err := m.DeviceID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipControlplane(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthControlplane
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipControlplane(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowControlplane
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthControlplane
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupControlplane
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthControlplane
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthControlplane        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowControlplane          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupControlplane = fmt.Errorf("proto: unexpected end of group")
)
