// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: src/api/corepb/v1/controlplane.proto

package corepb

import (
	fmt "fmt"
	typespb "gimletlabs.ai/gimlet/src/common/typespb"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CPTopic int32

const (
	CP_TOPIC_UNKNOWN                 CPTopic = 0
	CP_TOPIC_DEVICE_CONNECTED        CPTopic = 1
	CP_TOPIC_PIPELINE_RECONCILIATION CPTopic = 2
)

var CPTopic_name = map[int32]string{
	0: "CP_TOPIC_UNKNOWN",
	1: "CP_TOPIC_DEVICE_CONNECTED",
	2: "CP_TOPIC_PIPELINE_RECONCILIATION",
}

var CPTopic_value = map[string]int32{
	"CP_TOPIC_UNKNOWN":                 0,
	"CP_TOPIC_DEVICE_CONNECTED":        1,
	"CP_TOPIC_PIPELINE_RECONCILIATION": 2,
}

func (CPTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7c2de589f3a2dd8, []int{0}
}

type CPMetadata struct {
	Topic         CPTopic          `protobuf:"varint,1,opt,name=topic,proto3,enum=gml.internal.api.core.v1.CPTopic" json:"topic,omitempty"`
	DeviceID      *typespb.UUID    `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RecvTimestamp *types.Timestamp `protobuf:"bytes,3,opt,name=recv_timestamp,json=recvTimestamp,proto3" json:"recv_timestamp,omitempty"`
}

func (m *CPMetadata) Reset()      { *m = CPMetadata{} }
func (*CPMetadata) ProtoMessage() {}
func (*CPMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c2de589f3a2dd8, []int{0}
}
func (m *CPMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CPMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CPMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CPMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPMetadata.Merge(m, src)
}
func (m *CPMetadata) XXX_Size() int {
	return m.Size()
}
func (m *CPMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_CPMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_CPMetadata proto.InternalMessageInfo

func (m *CPMetadata) GetTopic() CPTopic {
	if m != nil {
		return m.Topic
	}
	return CP_TOPIC_UNKNOWN
}

func (m *CPMetadata) GetDeviceID() *typespb.UUID {
	if m != nil {
		return m.DeviceID
	}
	return nil
}

func (m *CPMetadata) GetRecvTimestamp() *types.Timestamp {
	if m != nil {
		return m.RecvTimestamp
	}
	return nil
}

type CPMessage struct {
	Metadata *CPMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Msg      *types.Any  `protobuf:"bytes,1000,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *CPMessage) Reset()      { *m = CPMessage{} }
func (*CPMessage) ProtoMessage() {}
func (*CPMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c2de589f3a2dd8, []int{1}
}
func (m *CPMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CPMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CPMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CPMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPMessage.Merge(m, src)
}
func (m *CPMessage) XXX_Size() int {
	return m.Size()
}
func (m *CPMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CPMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CPMessage proto.InternalMessageInfo

func (m *CPMessage) GetMetadata() *CPMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CPMessage) GetMsg() *types.Any {
	if m != nil {
		return m.Msg
	}
	return nil
}

type DeviceConnected struct {
	DeviceID *typespb.UUID `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
}

func (m *DeviceConnected) Reset()      { *m = DeviceConnected{} }
func (*DeviceConnected) ProtoMessage() {}
func (*DeviceConnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c2de589f3a2dd8, []int{2}
}
func (m *DeviceConnected) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceConnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceConnected.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeviceConnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceConnected.Merge(m, src)
}
func (m *DeviceConnected) XXX_Size() int {
	return m.Size()
}
func (m *DeviceConnected) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceConnected.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceConnected proto.InternalMessageInfo

func (m *DeviceConnected) GetDeviceID() *typespb.UUID {
	if m != nil {
		return m.DeviceID
	}
	return nil
}

type PipelineReconciliation struct {
	DeviceID   *typespb.UUID `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PipelineID *typespb.UUID `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
}

func (m *PipelineReconciliation) Reset()      { *m = PipelineReconciliation{} }
func (*PipelineReconciliation) ProtoMessage() {}
func (*PipelineReconciliation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c2de589f3a2dd8, []int{3}
}
func (m *PipelineReconciliation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PipelineReconciliation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PipelineReconciliation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PipelineReconciliation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineReconciliation.Merge(m, src)
}
func (m *PipelineReconciliation) XXX_Size() int {
	return m.Size()
}
func (m *PipelineReconciliation) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineReconciliation.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineReconciliation proto.InternalMessageInfo

func (m *PipelineReconciliation) GetDeviceID() *typespb.UUID {
	if m != nil {
		return m.DeviceID
	}
	return nil
}

func (m *PipelineReconciliation) GetPipelineID() *typespb.UUID {
	if m != nil {
		return m.PipelineID
	}
	return nil
}

func init() {
	proto.RegisterEnum("gml.internal.api.core.v1.CPTopic", CPTopic_name, CPTopic_value)
	proto.RegisterType((*CPMetadata)(nil), "gml.internal.api.core.v1.CPMetadata")
	proto.RegisterType((*CPMessage)(nil), "gml.internal.api.core.v1.CPMessage")
	proto.RegisterType((*DeviceConnected)(nil), "gml.internal.api.core.v1.DeviceConnected")
	proto.RegisterType((*PipelineReconciliation)(nil), "gml.internal.api.core.v1.PipelineReconciliation")
}

func init() {
	proto.RegisterFile("src/api/corepb/v1/controlplane.proto", fileDescriptor_f7c2de589f3a2dd8)
}

var fileDescriptor_f7c2de589f3a2dd8 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x41, 0x6b, 0xdb, 0x3e,
	0x18, 0xc6, 0xad, 0x96, 0xff, 0xbf, 0xad, 0xba, 0xb5, 0xc1, 0x94, 0x91, 0x16, 0xaa, 0x66, 0x21,
	0xb0, 0x32, 0x98, 0x4c, 0xb3, 0xc3, 0x60, 0xbb, 0x34, 0xb5, 0x7d, 0x10, 0x6b, 0x1d, 0x63, 0x92,
	0x0d, 0x76, 0x31, 0x8a, 0xad, 0x19, 0x81, 0x2d, 0x19, 0x5b, 0x09, 0xe4, 0xb6, 0x8f, 0xb0, 0xd3,
	0x3e, 0xc3, 0x3e, 0xc8, 0x0e, 0x3b, 0xe6, 0xd8, 0x53, 0x59, 0x9c, 0x4b, 0x8f, 0xfd, 0x08, 0xc3,
	0x76, 0x12, 0xd8, 0xca, 0x0a, 0x63, 0x37, 0xbd, 0x7e, 0x7f, 0xcf, 0xeb, 0xe7, 0xd1, 0x8b, 0x60,
	0x27, 0xcf, 0x02, 0x83, 0xa6, 0xdc, 0x08, 0x64, 0xc6, 0xd2, 0x91, 0x31, 0x39, 0x33, 0x02, 0x29,
	0x54, 0x26, 0xe3, 0x34, 0xa6, 0x82, 0xe1, 0x34, 0x93, 0x4a, 0xea, 0xcd, 0x28, 0x89, 0x31, 0x17,
	0x8a, 0x65, 0x82, 0xc6, 0x98, 0xa6, 0x1c, 0x97, 0x38, 0x9e, 0x9c, 0x1d, 0x1d, 0x44, 0x32, 0x92,
	0x15, 0x64, 0x94, 0xa7, 0x9a, 0x3f, 0x3a, 0x2e, 0xa7, 0x06, 0x32, 0x49, 0xa4, 0x30, 0xd4, 0x34,
	0x65, 0x79, 0x3a, 0x32, 0xc6, 0x63, 0x1e, 0x2e, 0xdb, 0x87, 0x91, 0x94, 0x51, 0xcc, 0x8c, 0xaa,
	0x1a, 0x8d, 0x3f, 0x1a, 0x54, 0x4c, 0x97, 0xad, 0x93, 0xdf, 0x5b, 0x8a, 0x27, 0x2c, 0x57, 0x34,
	0x49, 0x6b, 0xa0, 0xfd, 0x0d, 0x40, 0x68, 0xba, 0x57, 0x4c, 0xd1, 0x90, 0x2a, 0xaa, 0xbf, 0x82,
	0xff, 0x29, 0x99, 0xf2, 0xa0, 0x09, 0x5a, 0xe0, 0x74, 0xaf, 0xfb, 0x14, 0xff, 0xc9, 0x29, 0x36,
	0xdd, 0x41, 0x09, 0x7a, 0x35, 0xaf, 0xbf, 0x86, 0x3b, 0x21, 0x9b, 0xf0, 0x80, 0xf9, 0x3c, 0x6c,
	0x6e, 0xb4, 0xc0, 0xe9, 0x6e, 0x77, 0xbf, 0x12, 0x57, 0x7e, 0xf1, 0x70, 0x48, 0xac, 0x8b, 0x47,
	0xc5, 0xcd, 0xc9, 0xb6, 0x55, 0x51, 0xc4, 0xf2, 0xb6, 0x6b, 0x9e, 0x84, 0x7a, 0x0f, 0xee, 0x65,
	0x2c, 0x98, 0xf8, 0x6b, 0x6f, 0xcd, 0xcd, 0x6a, 0xc0, 0x11, 0xae, 0xdd, 0xe3, 0x95, 0x7b, 0x3c,
	0x58, 0x11, 0xde, 0xe3, 0x52, 0xb1, 0x2e, 0xdb, 0x13, 0xb8, 0x53, 0xa6, 0xc8, 0x73, 0x1a, 0x31,
	0xfd, 0x1c, 0x6e, 0x27, 0xcb, 0x40, 0x55, 0x8e, 0xdd, 0x6e, 0xe7, 0xa1, 0x1c, 0xab, 0xf0, 0xde,
	0x5a, 0xa5, 0x3f, 0x83, 0x9b, 0x49, 0x1e, 0x35, 0x6f, 0xb7, 0x2a, 0xf5, 0xc1, 0x3d, 0x1f, 0x3d,
	0x31, 0xf5, 0x4a, 0xa2, 0x7d, 0x05, 0xf7, 0xeb, 0x40, 0xa6, 0x14, 0x82, 0x05, 0x8a, 0x85, 0xbf,
	0xde, 0x04, 0xf8, 0xab, 0x9b, 0x68, 0x7f, 0x01, 0xf0, 0x89, 0xcb, 0x53, 0x16, 0x73, 0xc1, 0x3c,
	0x16, 0x48, 0x11, 0xf0, 0x98, 0x53, 0xc5, 0xa5, 0xf8, 0x97, 0xb1, 0xfa, 0x39, 0xdc, 0x4d, 0x97,
	0x53, 0x1f, 0x58, 0xcf, 0x5e, 0x71, 0x73, 0x02, 0x57, 0x7f, 0x27, 0x96, 0x07, 0x57, 0x1a, 0x12,
	0x3e, 0x0f, 0xe1, 0xd6, 0x72, 0xe1, 0xfa, 0x01, 0x6c, 0x98, 0xae, 0x3f, 0xe8, 0xbb, 0xc4, 0xf4,
	0x87, 0xce, 0x5b, 0xa7, 0xff, 0xde, 0x69, 0x68, 0xfa, 0x31, 0x3c, 0x5c, 0x7f, 0xb5, 0xec, 0x77,
	0xc4, 0xb4, 0x7d, 0xb3, 0xef, 0x38, 0xb6, 0x39, 0xb0, 0xad, 0x06, 0xd0, 0x3b, 0xb0, 0xb5, 0x6e,
	0xbb, 0xc4, 0xb5, 0x2f, 0x89, 0x63, 0xfb, 0x9e, 0x6d, 0xf6, 0x1d, 0x93, 0x5c, 0x92, 0xde, 0x80,
	0xf4, 0x9d, 0xc6, 0xc6, 0x45, 0x30, 0x9b, 0x23, 0xed, 0x7a, 0x8e, 0xb4, 0xbb, 0x39, 0x02, 0x9f,
	0x0a, 0x04, 0xbe, 0x16, 0x08, 0x7c, 0x2f, 0x10, 0x98, 0x15, 0x08, 0xfc, 0x28, 0x10, 0xb8, 0x2d,
	0x90, 0x76, 0x57, 0x20, 0xf0, 0x79, 0x81, 0xb4, 0xd9, 0x02, 0x69, 0xd7, 0x0b, 0xa4, 0x7d, 0x78,
	0x11, 0xf1, 0x24, 0x66, 0x2a, 0xa6, 0xa3, 0x1c, 0x53, 0x6e, 0xd4, 0x95, 0x71, 0xef, 0x21, 0xbe,
	0xa9, 0x4f, 0xa3, 0xff, 0xab, 0x2d, 0xbe, 0xfc, 0x19, 0x00, 0x00, 0xff, 0xff, 0x90, 0x20, 0x7a,
	0x55, 0xab, 0x03, 0x00, 0x00,
}

func (x CPTopic) String() string {
	s, ok := CPTopic_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *CPMetadata) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CPMetadata)
	if !ok {
		that2, ok := that.(CPMetadata)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Topic != that1.Topic {
		return false
	}
	if !this.DeviceID.Equal(that1.DeviceID) {
		return false
	}
	if !this.RecvTimestamp.Equal(that1.RecvTimestamp) {
		return false
	}
	return true
}
func (this *CPMessage) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CPMessage)
	if !ok {
		that2, ok := that.(CPMessage)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Metadata.Equal(that1.Metadata) {
		return false
	}
	if !this.Msg.Equal(that1.Msg) {
		return false
	}
	return true
}
func (this *DeviceConnected) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DeviceConnected)
	if !ok {
		that2, ok := that.(DeviceConnected)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DeviceID.Equal(that1.DeviceID) {
		return false
	}
	return true
}
func (this *PipelineReconciliation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PipelineReconciliation)
	if !ok {
		that2, ok := that.(PipelineReconciliation)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DeviceID.Equal(that1.DeviceID) {
		return false
	}
	if !this.PipelineID.Equal(that1.PipelineID) {
		return false
	}
	return true
}
func (this *CPMetadata) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&corepb.CPMetadata{")
	s = append(s, "Topic: "+fmt.Sprintf("%#v", this.Topic)+",\n")
	if this.DeviceID != nil {
		s = append(s, "DeviceID: "+fmt.Sprintf("%#v", this.DeviceID)+",\n")
	}
	if this.RecvTimestamp != nil {
		s = append(s, "RecvTimestamp: "+fmt.Sprintf("%#v", this.RecvTimestamp)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CPMessage) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&corepb.CPMessage{")
	if this.Metadata != nil {
		s = append(s, "Metadata: "+fmt.Sprintf("%#v", this.Metadata)+",\n")
	}
	if this.Msg != nil {
		s = append(s, "Msg: "+fmt.Sprintf("%#v", this.Msg)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeviceConnected) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&corepb.DeviceConnected{")
	if this.DeviceID != nil {
		s = append(s, "DeviceID: "+fmt.Sprintf("%#v", this.DeviceID)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *PipelineReconciliation) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&corepb.PipelineReconciliation{")
	if this.DeviceID != nil {
		s = append(s, "DeviceID: "+fmt.Sprintf("%#v", this.DeviceID)+",\n")
	}
	if this.PipelineID != nil {
		s = append(s, "PipelineID: "+fmt.Sprintf("%#v", this.PipelineID)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringControlplane(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *CPMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CPMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RecvTimestamp != nil {
		{
			size, err := m.RecvTimestamp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintControlplane(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.DeviceID != nil {
		{
			size, err := m.DeviceID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintControlplane(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Topic != 0 {
		i = encodeVarintControlplane(dAtA, i, uint64(m.Topic))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CPMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CPMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Msg != nil {
		{
			size, err := m.Msg.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintControlplane(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3e
		i--
		dAtA[i] = 0xc2
	}
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintControlplane(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeviceConnected) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceConnected) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeviceConnected) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeviceID != nil {
		{
			size, err := m.DeviceID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintControlplane(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PipelineReconciliation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PipelineReconciliation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PipelineReconciliation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PipelineID != nil {
		{
			size, err := m.PipelineID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintControlplane(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.DeviceID != nil {
		{
			size, err := m.DeviceID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintControlplane(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintControlplane(dAtA []byte, offset int, v uint64) int {
	offset -= sovControlplane(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CPMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Topic != 0 {
		n += 1 + sovControlplane(uint64(m.Topic))
	}
	if m.DeviceID != nil {
		l = m.DeviceID.Size()
		n += 1 + l + sovControlplane(uint64(l))
	}
	if m.RecvTimestamp != nil {
		l = m.RecvTimestamp.Size()
		n += 1 + l + sovControlplane(uint64(l))
	}
	return n
}

func (m *CPMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovControlplane(uint64(l))
	}
	if m.Msg != nil {
		l = m.Msg.Size()
		n += 2 + l + sovControlplane(uint64(l))
	}
	return n
}

func (m *DeviceConnected) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DeviceID != nil {
		l = m.DeviceID.Size()
		n += 1 + l + sovControlplane(uint64(l))
	}
	return n
}

func (m *PipelineReconciliation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DeviceID != nil {
		l = m.DeviceID.Size()
		n += 1 + l + sovControlplane(uint64(l))
	}
	if m.PipelineID != nil {
		l = m.PipelineID.Size()
		n += 1 + l + sovControlplane(uint64(l))
	}
	return n
}

func sovControlplane(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozControlplane(x uint64) (n int) {
	return sovControlplane(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CPMetadata) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CPMetadata{`,
		`Topic:` + fmt.Sprintf("%v", this.Topic) + `,`,
		`DeviceID:` + strings.Replace(fmt.Sprintf("%v", this.DeviceID), "UUID", "typespb.UUID", 1) + `,`,
		`RecvTimestamp:` + strings.Replace(fmt.Sprintf("%v", this.RecvTimestamp), "Timestamp", "types.Timestamp", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CPMessage) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CPMessage{`,
		`Metadata:` + strings.Replace(this.Metadata.String(), "CPMetadata", "CPMetadata", 1) + `,`,
		`Msg:` + strings.Replace(fmt.Sprintf("%v", this.Msg), "Any", "types.Any", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeviceConnected) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeviceConnected{`,
		`DeviceID:` + strings.Replace(fmt.Sprintf("%v", this.DeviceID), "UUID", "typespb.UUID", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PipelineReconciliation) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PipelineReconciliation{`,
		`DeviceID:` + strings.Replace(fmt.Sprintf("%v", this.DeviceID), "UUID", "typespb.UUID", 1) + `,`,
		`PipelineID:` + strings.Replace(fmt.Sprintf("%v", this.PipelineID), "UUID", "typespb.UUID", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringControlplane(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CPMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowControlplane
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topic", wireType)
			}
			m.Topic = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Topic |= CPTopic(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthControlplane
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthControlplane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeviceID == nil {
				m.DeviceID = &typespb.UUID{}
			}
			if err := m.DeviceID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecvTimestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthControlplane
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthControlplane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RecvTimestamp == nil {
				m.RecvTimestamp = &types.Timestamp{}
			}
			if err := m.RecvTimestamp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipControlplane(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthControlplane
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CPMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowControlplane
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthControlplane
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthControlplane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &CPMetadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 1000:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthControlplane
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthControlplane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Msg == nil {
				m.Msg = &types.Any{}
			}
			if err := m.Msg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipControlplane(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthControlplane
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeviceConnected) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowControlplane
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceConnected: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceConnected: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthControlplane
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthControlplane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeviceID == nil {
				m.DeviceID = &typespb.UUID{}
			}
			if err := m.DeviceID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipControlplane(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthControlplane
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PipelineReconciliation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowControlplane
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PipelineReconciliation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PipelineReconciliation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthControlplane
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthControlplane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeviceID == nil {
				m.DeviceID = &typespb.UUID{}
			}
			if err := m.DeviceID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PipelineID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthControlplane
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthControlplane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PipelineID == nil {
				m.PipelineID = &typespb.UUID{}
			}
			if err := m.PipelineID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipControlplane(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthControlplane
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipControlplane(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowControlplane
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowControlplane
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthControlplane
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupControlplane
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthControlplane
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthControlplane        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowControlplane          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupControlplane = fmt.Errorf("proto: unexpected end of group")
)
