// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: src/gem/calculators/core/optionspb/generate_chat_message_calculator_options.proto

package optionspb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenerateChatMessageCalculatorOptions struct {
	MessageTemplate     string `protobuf:"bytes,1,opt,name=message_template,json=messageTemplate,proto3" json:"message_template,omitempty"`
	PresetSystemPrompt  string `protobuf:"bytes,2,opt,name=preset_system_prompt,json=presetSystemPrompt,proto3" json:"preset_system_prompt,omitempty"`
	AddGenerationPrompt bool   `protobuf:"varint,3,opt,name=add_generation_prompt,json=addGenerationPrompt,proto3" json:"add_generation_prompt,omitempty"`
}

func (m *GenerateChatMessageCalculatorOptions) Reset()      { *m = GenerateChatMessageCalculatorOptions{} }
func (*GenerateChatMessageCalculatorOptions) ProtoMessage() {}
func (*GenerateChatMessageCalculatorOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a36ae800b535238, []int{0}
}
func (m *GenerateChatMessageCalculatorOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenerateChatMessageCalculatorOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenerateChatMessageCalculatorOptions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenerateChatMessageCalculatorOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateChatMessageCalculatorOptions.Merge(m, src)
}
func (m *GenerateChatMessageCalculatorOptions) XXX_Size() int {
	return m.Size()
}
func (m *GenerateChatMessageCalculatorOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateChatMessageCalculatorOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateChatMessageCalculatorOptions proto.InternalMessageInfo

func (m *GenerateChatMessageCalculatorOptions) GetMessageTemplate() string {
	if m != nil {
		return m.MessageTemplate
	}
	return ""
}

func (m *GenerateChatMessageCalculatorOptions) GetPresetSystemPrompt() string {
	if m != nil {
		return m.PresetSystemPrompt
	}
	return ""
}

func (m *GenerateChatMessageCalculatorOptions) GetAddGenerationPrompt() bool {
	if m != nil {
		return m.AddGenerationPrompt
	}
	return false
}

func init() {
	proto.RegisterType((*GenerateChatMessageCalculatorOptions)(nil), "gml.gem.calculators.core.optionspb.GenerateChatMessageCalculatorOptions")
}

func init() {
	proto.RegisterFile("src/gem/calculators/core/optionspb/generate_chat_message_calculator_options.proto", fileDescriptor_2a36ae800b535238)
}

var fileDescriptor_2a36ae800b535238 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x31, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x63, 0x90, 0x10, 0x64, 0x01, 0x05, 0x90, 0x3a, 0x3d, 0x55, 0x15, 0x43, 0x59, 0x62,
	0x04, 0x23, 0x13, 0x74, 0xe8, 0x84, 0x80, 0xc2, 0xc4, 0x62, 0xb9, 0xc9, 0x53, 0x1a, 0xc9, 0xae,
	0x2d, 0xfb, 0x21, 0xc4, 0xc6, 0x11, 0x38, 0x06, 0x37, 0xe0, 0x0a, 0x8c, 0x1d, 0x3b, 0x52, 0x77,
	0x61, 0xec, 0x11, 0x10, 0x49, 0x1a, 0xd8, 0xd8, 0xec, 0xf7, 0xff, 0xdf, 0x67, 0xf9, 0xc5, 0xb7,
	0xde, 0x65, 0xbc, 0x40, 0xcd, 0x33, 0xa9, 0xb2, 0x47, 0x25, 0xc9, 0x38, 0xcf, 0x33, 0xe3, 0x90,
	0x1b, 0x4b, 0xa5, 0x99, 0x7a, 0x3b, 0xe6, 0x05, 0x4e, 0xd1, 0x49, 0x42, 0x91, 0x4d, 0x24, 0x09,
	0x8d, 0xde, 0xcb, 0x02, 0xc5, 0x2f, 0x20, 0x9a, 0x6a, 0x6a, 0x9d, 0x21, 0x93, 0xf4, 0x0a, 0xad,
	0xd2, 0x02, 0x75, 0xfa, 0x47, 0x99, 0xfe, 0x28, 0xd3, 0x56, 0xd9, 0x7b, 0x67, 0xf1, 0xd1, 0xb0,
	0xd1, 0x0e, 0x26, 0x92, 0xae, 0x6a, 0xe9, 0xa0, 0x25, 0xae, 0xeb, 0x6a, 0x72, 0x1c, 0xef, 0xad,
	0x1f, 0x24, 0xd4, 0x56, 0x49, 0xc2, 0x0e, 0xeb, 0xb2, 0xfe, 0xce, 0x68, 0xb7, 0x99, 0xdf, 0x37,
	0xe3, 0xe4, 0x24, 0x3e, 0xb0, 0x0e, 0x3d, 0x92, 0xf0, 0xcf, 0x9e, 0x50, 0x0b, 0xeb, 0x8c, 0xb6,
	0xd4, 0xd9, 0xa8, 0xea, 0x49, 0x9d, 0xdd, 0x55, 0xd1, 0x4d, 0x95, 0x24, 0xa7, 0xf1, 0xa1, 0xcc,
	0x73, 0xd1, 0xfc, 0xaf, 0x34, 0xd3, 0x35, 0xb2, 0xd9, 0x65, 0xfd, 0xed, 0xd1, 0xbe, 0xcc, 0xf3,
	0x61, 0x9b, 0xd5, 0xcc, 0xe5, 0xd3, 0x6c, 0x01, 0xd1, 0x7c, 0x01, 0xd1, 0x6a, 0x01, 0xec, 0x25,
	0x00, 0x7b, 0x0b, 0xc0, 0x3e, 0x02, 0xb0, 0x59, 0x00, 0xf6, 0x19, 0x80, 0x7d, 0x05, 0x88, 0x56,
	0x01, 0xd8, 0xeb, 0x12, 0xa2, 0xd9, 0x12, 0xa2, 0xf9, 0x12, 0xa2, 0x87, 0x8b, 0xa2, 0xd4, 0x0a,
	0x49, 0xc9, 0xb1, 0x4f, 0x65, 0xc9, 0xeb, 0x1b, 0xff, 0x7f, 0xf7, 0xe7, 0xed, 0x69, 0xbc, 0x55,
	0x6d, 0xf7, 0xec, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x79, 0x15, 0xdd, 0x61, 0xb2, 0x01, 0x00, 0x00,
}

func (this *GenerateChatMessageCalculatorOptions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenerateChatMessageCalculatorOptions)
	if !ok {
		that2, ok := that.(GenerateChatMessageCalculatorOptions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MessageTemplate != that1.MessageTemplate {
		return false
	}
	if this.PresetSystemPrompt != that1.PresetSystemPrompt {
		return false
	}
	if this.AddGenerationPrompt != that1.AddGenerationPrompt {
		return false
	}
	return true
}
func (this *GenerateChatMessageCalculatorOptions) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&optionspb.GenerateChatMessageCalculatorOptions{")
	s = append(s, "MessageTemplate: "+fmt.Sprintf("%#v", this.MessageTemplate)+",\n")
	s = append(s, "PresetSystemPrompt: "+fmt.Sprintf("%#v", this.PresetSystemPrompt)+",\n")
	s = append(s, "AddGenerationPrompt: "+fmt.Sprintf("%#v", this.AddGenerationPrompt)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringGenerateChatMessageCalculatorOptions(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *GenerateChatMessageCalculatorOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenerateChatMessageCalculatorOptions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenerateChatMessageCalculatorOptions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AddGenerationPrompt {
		i--
		if m.AddGenerationPrompt {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.PresetSystemPrompt) > 0 {
		i -= len(m.PresetSystemPrompt)
		copy(dAtA[i:], m.PresetSystemPrompt)
		i = encodeVarintGenerateChatMessageCalculatorOptions(dAtA, i, uint64(len(m.PresetSystemPrompt)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MessageTemplate) > 0 {
		i -= len(m.MessageTemplate)
		copy(dAtA[i:], m.MessageTemplate)
		i = encodeVarintGenerateChatMessageCalculatorOptions(dAtA, i, uint64(len(m.MessageTemplate)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenerateChatMessageCalculatorOptions(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerateChatMessageCalculatorOptions(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenerateChatMessageCalculatorOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MessageTemplate)
	if l > 0 {
		n += 1 + l + sovGenerateChatMessageCalculatorOptions(uint64(l))
	}
	l = len(m.PresetSystemPrompt)
	if l > 0 {
		n += 1 + l + sovGenerateChatMessageCalculatorOptions(uint64(l))
	}
	if m.AddGenerationPrompt {
		n += 2
	}
	return n
}

func sovGenerateChatMessageCalculatorOptions(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerateChatMessageCalculatorOptions(x uint64) (n int) {
	return sovGenerateChatMessageCalculatorOptions(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *GenerateChatMessageCalculatorOptions) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GenerateChatMessageCalculatorOptions{`,
		`MessageTemplate:` + fmt.Sprintf("%v", this.MessageTemplate) + `,`,
		`PresetSystemPrompt:` + fmt.Sprintf("%v", this.PresetSystemPrompt) + `,`,
		`AddGenerationPrompt:` + fmt.Sprintf("%v", this.AddGenerationPrompt) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerateChatMessageCalculatorOptions(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *GenerateChatMessageCalculatorOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerateChatMessageCalculatorOptions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenerateChatMessageCalculatorOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenerateChatMessageCalculatorOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageTemplate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerateChatMessageCalculatorOptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerateChatMessageCalculatorOptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerateChatMessageCalculatorOptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageTemplate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PresetSystemPrompt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerateChatMessageCalculatorOptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerateChatMessageCalculatorOptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerateChatMessageCalculatorOptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PresetSystemPrompt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddGenerationPrompt", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerateChatMessageCalculatorOptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AddGenerationPrompt = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenerateChatMessageCalculatorOptions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerateChatMessageCalculatorOptions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerateChatMessageCalculatorOptions(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerateChatMessageCalculatorOptions
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerateChatMessageCalculatorOptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerateChatMessageCalculatorOptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerateChatMessageCalculatorOptions
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerateChatMessageCalculatorOptions
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerateChatMessageCalculatorOptions
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerateChatMessageCalculatorOptions        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerateChatMessageCalculatorOptions          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerateChatMessageCalculatorOptions = fmt.Errorf("proto: unexpected end of group")
)
