// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: src/gem/calculators/plugin/opencv_cam/optionspb/opencv_cam_calculator_options.proto

package optionspb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OpenCVCamSourceCalculatorOptions struct {
	DeviceFilename string `protobuf:"bytes,1,opt,name=device_filename,json=deviceFilename,proto3" json:"device_filename,omitempty"`
	MaxNumFrames   uint64 `protobuf:"varint,1000,opt,name=max_num_frames,json=maxNumFrames,proto3" json:"max_num_frames,omitempty"`
}

func (m *OpenCVCamSourceCalculatorOptions) Reset()      { *m = OpenCVCamSourceCalculatorOptions{} }
func (*OpenCVCamSourceCalculatorOptions) ProtoMessage() {}
func (*OpenCVCamSourceCalculatorOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_8acbde18ae09092d, []int{0}
}
func (m *OpenCVCamSourceCalculatorOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OpenCVCamSourceCalculatorOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OpenCVCamSourceCalculatorOptions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OpenCVCamSourceCalculatorOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenCVCamSourceCalculatorOptions.Merge(m, src)
}
func (m *OpenCVCamSourceCalculatorOptions) XXX_Size() int {
	return m.Size()
}
func (m *OpenCVCamSourceCalculatorOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenCVCamSourceCalculatorOptions.DiscardUnknown(m)
}

var xxx_messageInfo_OpenCVCamSourceCalculatorOptions proto.InternalMessageInfo

func (m *OpenCVCamSourceCalculatorOptions) GetDeviceFilename() string {
	if m != nil {
		return m.DeviceFilename
	}
	return ""
}

func (m *OpenCVCamSourceCalculatorOptions) GetMaxNumFrames() uint64 {
	if m != nil {
		return m.MaxNumFrames
	}
	return 0
}

func init() {
	proto.RegisterType((*OpenCVCamSourceCalculatorOptions)(nil), "gml.gem.calculators.opencv_cam.optionspb.OpenCVCamSourceCalculatorOptions")
}

func init() {
	proto.RegisterFile("src/gem/calculators/plugin/opencv_cam/optionspb/opencv_cam_calculator_options.proto", fileDescriptor_8acbde18ae09092d)
}

var fileDescriptor_8acbde18ae09092d = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x31, 0x6a, 0x2b, 0x31,
	0x10, 0x86, 0x25, 0x78, 0xbc, 0x90, 0x25, 0x38, 0xe0, 0xca, 0xd5, 0x60, 0x02, 0x21, 0xae, 0xa4,
	0x22, 0x65, 0xba, 0x18, 0x5c, 0xda, 0x60, 0x43, 0x8a, 0x34, 0x42, 0x56, 0xe4, 0x45, 0xa0, 0x91,
	0x84, 0x76, 0xd7, 0xb8, 0x4c, 0x91, 0x03, 0xe4, 0x18, 0x39, 0x4a, 0x4a, 0x97, 0x2e, 0xb3, 0xda,
	0xc6, 0xa5, 0x8f, 0x10, 0xf0, 0x9a, 0xb5, 0xdb, 0x74, 0x33, 0xdf, 0xcc, 0xf7, 0x17, 0x7f, 0xb6,
	0x28, 0xa2, 0xe2, 0xb9, 0x46, 0xae, 0xa4, 0x55, 0x95, 0x95, 0xa5, 0x8f, 0x05, 0x0f, 0xb6, 0xca,
	0x8d, 0xe3, 0x3e, 0x68, 0xa7, 0xd6, 0x42, 0x49, 0xe4, 0x3e, 0x94, 0xc6, 0xbb, 0x22, 0x2c, 0x2f,
	0xa0, 0x38, 0x2b, 0xe2, 0x74, 0x67, 0x21, 0xfa, 0xd2, 0xf7, 0x47, 0x39, 0x5a, 0x96, 0x6b, 0x64,
	0x17, 0xa1, 0xec, 0x2c, 0xb2, 0x2e, 0xed, 0x2e, 0x66, 0xc3, 0x59, 0xd0, 0x6e, 0xfc, 0x32, 0x96,
	0xb8, 0xf0, 0x55, 0x54, 0x7a, 0xdc, 0x29, 0xb3, 0xf6, 0xab, 0xff, 0x90, 0xdd, 0xbe, 0xe9, 0xb5,
	0x51, 0x5a, 0xac, 0x8c, 0xd5, 0x4e, 0xa2, 0x1e, 0xd0, 0x21, 0x1d, 0x5d, 0xcf, 0x7b, 0x2d, 0x9e,
	0x9c, 0x68, 0xff, 0x3e, 0xeb, 0xa1, 0xdc, 0x08, 0x57, 0xa1, 0x58, 0x45, 0x89, 0xba, 0x18, 0xec,
	0xaf, 0x86, 0x74, 0xf4, 0x6f, 0x7e, 0x83, 0x72, 0x33, 0xad, 0x70, 0x72, 0x84, 0xcf, 0x1f, 0x74,
	0x5b, 0x03, 0xd9, 0xd5, 0x40, 0x0e, 0x35, 0xd0, 0xf7, 0x04, 0xf4, 0x2b, 0x01, 0xfd, 0x4e, 0x40,
	0xb7, 0x09, 0xe8, 0x4f, 0x02, 0xba, 0x4f, 0x40, 0x0e, 0x09, 0xe8, 0x67, 0x03, 0x64, 0xdb, 0x00,
	0xd9, 0x35, 0x40, 0x5e, 0xa7, 0xb9, 0x41, 0xab, 0x4b, 0x2b, 0x97, 0x05, 0x93, 0x86, 0xb7, 0x1b,
	0xff, 0x63, 0x7d, 0x4f, 0xdd, 0xb4, 0xfc, 0x7f, 0xec, 0xea, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x50, 0x95, 0x2b, 0x41, 0x82, 0x01, 0x00, 0x00,
}

func (this *OpenCVCamSourceCalculatorOptions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OpenCVCamSourceCalculatorOptions)
	if !ok {
		that2, ok := that.(OpenCVCamSourceCalculatorOptions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.DeviceFilename != that1.DeviceFilename {
		return false
	}
	if this.MaxNumFrames != that1.MaxNumFrames {
		return false
	}
	return true
}
func (this *OpenCVCamSourceCalculatorOptions) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&optionspb.OpenCVCamSourceCalculatorOptions{")
	s = append(s, "DeviceFilename: "+fmt.Sprintf("%#v", this.DeviceFilename)+",\n")
	s = append(s, "MaxNumFrames: "+fmt.Sprintf("%#v", this.MaxNumFrames)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringOpencvCamCalculatorOptions(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *OpenCVCamSourceCalculatorOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OpenCVCamSourceCalculatorOptions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OpenCVCamSourceCalculatorOptions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxNumFrames != 0 {
		i = encodeVarintOpencvCamCalculatorOptions(dAtA, i, uint64(m.MaxNumFrames))
		i--
		dAtA[i] = 0x3e
		i--
		dAtA[i] = 0xc0
	}
	if len(m.DeviceFilename) > 0 {
		i -= len(m.DeviceFilename)
		copy(dAtA[i:], m.DeviceFilename)
		i = encodeVarintOpencvCamCalculatorOptions(dAtA, i, uint64(len(m.DeviceFilename)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintOpencvCamCalculatorOptions(dAtA []byte, offset int, v uint64) int {
	offset -= sovOpencvCamCalculatorOptions(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OpenCVCamSourceCalculatorOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DeviceFilename)
	if l > 0 {
		n += 1 + l + sovOpencvCamCalculatorOptions(uint64(l))
	}
	if m.MaxNumFrames != 0 {
		n += 2 + sovOpencvCamCalculatorOptions(uint64(m.MaxNumFrames))
	}
	return n
}

func sovOpencvCamCalculatorOptions(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOpencvCamCalculatorOptions(x uint64) (n int) {
	return sovOpencvCamCalculatorOptions(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *OpenCVCamSourceCalculatorOptions) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&OpenCVCamSourceCalculatorOptions{`,
		`DeviceFilename:` + fmt.Sprintf("%v", this.DeviceFilename) + `,`,
		`MaxNumFrames:` + fmt.Sprintf("%v", this.MaxNumFrames) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringOpencvCamCalculatorOptions(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *OpenCVCamSourceCalculatorOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOpencvCamCalculatorOptions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OpenCVCamSourceCalculatorOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OpenCVCamSourceCalculatorOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceFilename", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpencvCamCalculatorOptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpencvCamCalculatorOptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOpencvCamCalculatorOptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceFilename = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 1000:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNumFrames", wireType)
			}
			m.MaxNumFrames = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpencvCamCalculatorOptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNumFrames |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOpencvCamCalculatorOptions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOpencvCamCalculatorOptions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOpencvCamCalculatorOptions(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOpencvCamCalculatorOptions
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOpencvCamCalculatorOptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOpencvCamCalculatorOptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOpencvCamCalculatorOptions
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOpencvCamCalculatorOptions
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOpencvCamCalculatorOptions
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOpencvCamCalculatorOptions        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOpencvCamCalculatorOptions          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOpencvCamCalculatorOptions = fmt.Errorf("proto: unexpected end of group")
)
