graph {
  input_side_packet: "ctrl_exec_ctx"

  node {
    calculator: "ArgusCamSourceSubgraph"
    input_stream: "FINISHED:video"
    output_stream: "frames"
    output_stream: "VIDEO_HEADER:video_header"
    output_stream: "ALLOW:frame_allowed"
  }
  node {
    calculator: "VideoEncoderSubgraph"
    input_stream: "frames"
    input_stream: "VIDEO_HEADER:video_header"
    output_stream: "video"
  }
  node {
    calculator: "ObjDetectionOverlayedVideoSinkSubgraph"
    input_side_packet: "EXEC_CTX:ctrl_exec_ctx"
    input_stream: "AV_PACKETS:video"
  }
}
