type: "ObjDetectionOverlayedVideoSinkSubgraph"
input_stream: "AV_PACKETS:encoded_av_packets"
input_stream: "VIDEO_HEADER:video_header"
input_stream: "DETECTIONS:detections"
input_stream: "IMAGE_QUALITY:quality"
input_stream: "IMAGE_HIST:hist"
input_side_packet: "EXEC_CTX:ctrl_exec_ctx"

node {
  calculator: "OverlayedFFmpegVideoSinkCalculator"
  input_side_packet: "EXEC_CTX:ctrl_exec_ctx"
  input_stream: "DETECTIONS:detections"
  input_stream: "AV_PACKETS:encoded_av_packets"
  input_stream: "VIDEO_HEADER:video_header"
  input_stream: "IMAGE_QUALITY:quality"
  input_stream: "IMAGE_HIST:hist"
}
