type: "ObjDetectionOverlayedVideoSinkSubgraph"
input_stream: "AV_PACKETS:encoded_av_packets"
input_stream: "DETECTIONS:detections"

node {
  calculator: "OverlayedFFmpegVideoSinkCalculator"
  input_side_packet: "EXEC_CTX:ctrl_exec_ctx"
  input_stream: "DETECTIONS:detections"
  input_stream: "AV_PACKETS:encoded_av_packets"
}
