type: "ProductModelTensorRTSubgraph"
input_side_packet: "CPU_EXEC_CTX:cpu_exec_ctx"
input_side_packet: "TENSORRT_EXEC_CTX:tensorrt_exec_ctx"
input_stream: "sampled_frames"
output_stream: "detections"


node {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:sampled_frames"
  output_stream: "IMAGE:scaled_frames"
  node_options {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 416
      output_height: 416
      scale_mode: SCALE_MODE_FIT
      padding_color {
        red: 128
        green: 128
        blue: 128
      }
    }
  }
}

node {
  calculator: "ImageShapeCPUTensorCalculator"
  input_side_packet: "EXEC_CTX:cpu_exec_ctx"
  input_stream: "IMAGE_FRAME:sampled_frames"
  output_stream: "IMAGE_SHAPE:image_shape"
}

node {
  calculator: "CPUTensorToCUDATensorCalculator"
  input_side_packet: "EXEC_CTX:tensorrt_exec_ctx"
  input_stream: "image_shape"
  output_stream: "image_shape_cuda"
}

node {
  calculator: "ImageFrameToCUDATensorCalculator"
  input_side_packet: "EXEC_CTX:tensorrt_exec_ctx"
  input_stream: "IMAGE_FRAME:scaled_frames"
  output_stream: "OUTPUT_TENSOR:image_tensor"
}

node {
  calculator: "TensorRTExecuteCalculator"
  input_side_packet: "EXEC_CTX:tensorrt_exec_ctx"
  input_stream: "image_tensor"
  input_stream: "image_shape_cuda"
  output_stream: "anchor_boxes"
  output_stream: "scores"
  output_stream: "selected_indices"
  node_options {
    [type.googleapis.com/gml.gem.calculators.tensorrt.optionspb.TensorRTExecuteCalculatorOptions] {
      input_onnx_name: "x"
      input_onnx_name: "shape"
      output_onnx_name: "Squeeze__232:0"
      output_onnx_name: "Transpose__233:0"
      output_onnx_name: "casted_indices"
    }
  }
}

node {
  calculator: "CUDATensorToCPUTensorCalculator"
  input_side_packet: "EXEC_CTX:cpu_exec_ctx"
  input_stream: "anchor_boxes"
  input_stream: "scores"
  input_stream: "selected_indices"
  output_stream: "anchor_boxes_cpu"
  output_stream: "scores_cpu"
  output_stream: "selected_indices_cpu"
}

node {
  calculator: "BoundingBoxTensorsToDetections"
  input_stream: "BOX_TENSOR:anchor_boxes_cpu"
  input_stream: "SCORE_TENSOR:scores_cpu"
  input_stream: "INDEX_TENSOR:selected_indices_cpu"
  input_stream: "ORIG_IMAGE_SHAPE:image_shape"
  output_stream: "detections"
  node_options {
    [type.googleapis.com/gml.gem.calculators.cpu_tensor.optionspb.BoundingBoxToDetectionsOptions] {
      # TODO(james): Pull these from a file/blob instead of listing them here.
      index_to_label: "product"
      coordinate_format: COORDINATE_FORMAT_NORMALIZED_DIAG_CORNERS_XY
    }
  }
}
