# Copyright © 2023- Gimlet Labs, Inc.
# All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Gimlet Labs, Inc. and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to Gimlet Labs, Inc. and its suppliers and
# may be covered by U.S. and Foreign Patents, patents in process,
# and are protected by trade secret or copyright law. Dissemination
# of this information or reproduction of this material is strictly
# forbidden unless prior written permission is obtained from
# Gimlet Labs, Inc.
#
# SPDX-License-Identifier: Proprietary

# THIS FILE IS GENERATED BY build_all_sysroots

load("//bazel/cc_toolchains/sysroots:sysroots.bzl", "sysroot_repo")

def _create_sysroots():
    sysroot_repo(
        name = "sysroot_aarch64_glibc2_36_runtime",
        target_arch = "aarch64",
        variant = "runtime",
        libc_version = "glibc2_36",
        sha256 = "fdcd47c30a7dfca069cbaa5e9cf07cfc914e1d3ca4c7daf8a96c68bfa02bfc1f",
        urls = ["https://storage.googleapis.com/gimlet-dev-infra-public/sysroots/20231120181642/sysroot-aarch64-glibc2_36-runtime.tar.gz"],
        sysroot_features = [],
        disabled_for_features = ["jetson"],
    )
    sysroot_repo(
        name = "sysroot_aarch64_glibc2_36_build",
        target_arch = "aarch64",
        variant = "build",
        libc_version = "glibc2_36",
        sha256 = "cf08dbeaea9726e40373dd93d2d398c333ba9eec938973c2c7871cad7a32c62f",
        urls = ["https://storage.googleapis.com/gimlet-dev-infra-public/sysroots/20231120181642/sysroot-aarch64-glibc2_36-build.tar.gz"],
        sysroot_features = [],
        disabled_for_features = ["jetson"],
    )
    sysroot_repo(
        name = "sysroot_aarch64_glibc2_36_test",
        target_arch = "aarch64",
        variant = "test",
        libc_version = "glibc2_36",
        sha256 = "de1a29f5c1e56f54f8f20587ada51a9859b680fbe5770688961101ad91a752c9",
        urls = ["https://storage.googleapis.com/gimlet-dev-infra-public/sysroots/20231120181642/sysroot-aarch64-glibc2_36-test.tar.gz"],
        sysroot_features = [],
        disabled_for_features = ["debug", "jetson"],
    )
    sysroot_repo(
        name = "sysroot_aarch64_glibc2_36_test_debug",
        target_arch = "aarch64",
        variant = "test",
        libc_version = "glibc2_36",
        sha256 = "c3393c321a2889e61d21c0e3f20cc441bd32b8bc78224fae9200158f1e2a36fb",
        urls = ["https://storage.googleapis.com/gimlet-dev-infra-public/sysroots/20231120181642/sysroot-aarch64-glibc2_36-test-debug.tar.gz"],
        sysroot_features = ["debug"],
        disabled_for_features = ["jetson"],
    )
    sysroot_repo(
        name = "sysroot_x86_64_glibc2_36_runtime",
        target_arch = "x86_64",
        variant = "runtime",
        libc_version = "glibc2_36",
        sha256 = "07f35cbdd6c782e2605a3033a325ca1a9a09aad172aec8e036682b9d4cb9b078",
        urls = ["https://storage.googleapis.com/gimlet-dev-infra-public/sysroots/20231120181642/sysroot-x86_64-glibc2_36-runtime.tar.gz"],
        sysroot_features = [],
        disabled_for_features = ["jetson"],
    )
    sysroot_repo(
        name = "sysroot_x86_64_glibc2_36_build",
        target_arch = "x86_64",
        variant = "build",
        libc_version = "glibc2_36",
        sha256 = "63f0f32135e0e6d13bb7281c55aa9bdcfc818c70b805d28cafa85b9a247a3e28",
        urls = ["https://storage.googleapis.com/gimlet-dev-infra-public/sysroots/20231120181642/sysroot-x86_64-glibc2_36-build.tar.gz"],
        sysroot_features = [],
        disabled_for_features = ["jetson"],
    )
    sysroot_repo(
        name = "sysroot_x86_64_glibc2_36_test",
        target_arch = "x86_64",
        variant = "test",
        libc_version = "glibc2_36",
        sha256 = "cb737ffd794ce0dc187ab6c8ec432a6bdd7500dec1138fa89036fdcb6d0e49e9",
        urls = ["https://storage.googleapis.com/gimlet-dev-infra-public/sysroots/20231120181642/sysroot-x86_64-glibc2_36-test.tar.gz"],
        sysroot_features = [],
        disabled_for_features = ["debug", "jetson"],
    )
    sysroot_repo(
        name = "sysroot_x86_64_glibc2_36_test_debug",
        target_arch = "x86_64",
        variant = "test",
        libc_version = "glibc2_36",
        sha256 = "d79f53655057ea5770c75c2afab3816b7a990693468fdbb34f47f36e6130bae6",
        urls = ["https://storage.googleapis.com/gimlet-dev-infra-public/sysroots/20231120181642/sysroot-x86_64-glibc2_36-test-debug.tar.gz"],
        sysroot_features = ["debug"],
        disabled_for_features = ["jetson"],
    )
    sysroot_repo(
        name = "sysroot_aarch64_glibc2_31_runtime_jetson",
        target_arch = "aarch64",
        variant = "runtime",
        libc_version = "glibc2_31",
        sha256 = "b86cf38aba03eea78cc95dd6911b53b7b814af09c0d0d9d6628f46af5359c26d",
        urls = ["https://storage.googleapis.com/gimlet-dev-infra-public/sysroots/20231120181642/sysroot-aarch64-glibc2_31-runtime-jetson.tar.gz"],
        sysroot_features = ["jetson"],
        disabled_for_features = [],
    )
    sysroot_repo(
        name = "sysroot_aarch64_glibc2_31_build_jetson",
        target_arch = "aarch64",
        variant = "build",
        libc_version = "glibc2_31",
        sha256 = "d872a182e22b36e66cf0da85d64fe8c4fac733983a1a9844ab6b2edbb78c5f90",
        urls = ["https://storage.googleapis.com/gimlet-dev-infra-public/sysroots/20231120181642/sysroot-aarch64-glibc2_31-build-jetson.tar.gz"],
        sysroot_features = ["jetson"],
        disabled_for_features = [],
    )
    sysroot_repo(
        name = "sysroot_aarch64_glibc2_31_test_jetson",
        target_arch = "aarch64",
        variant = "test",
        libc_version = "glibc2_31",
        sha256 = "3752afa488ad7374f999f82404d6cbf518995c626636f1bfa1ee479cb6770a25",
        urls = ["https://storage.googleapis.com/gimlet-dev-infra-public/sysroots/20231120181642/sysroot-aarch64-glibc2_31-test-jetson.tar.gz"],
        sysroot_features = ["jetson"],
        disabled_for_features = ["debug"],
    )

create_sysroots = _create_sysroots
